{
 "title": "code-status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "rps by job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (rate(api_request_code_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(api_request_code_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(api_request_code_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}